import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

const Color background = CupertinoColors.systemGroupedBackground;
const Color backgroundDark = CupertinoColors.lightBackgroundGray;

const Color white = Color(0xFFFFFFFF);
const Color whiteTransp = Color(0xC8FFFFFF);
const Color black = Color(0xFF000000);
const Color systemGrey1 = CupertinoColors.systemGrey;
const Color systemGrey2 = Color(0xFF49494B);
const Color systemGrey4 = CupertinoColors.systemGrey4;
const Color systemRed = CupertinoColors.systemRed;
const Color systemBlue = CupertinoColors.activeBlue;
const Color transp = Colors.transparent;

const Color lightRed = Color(0xFFFF5154);
const Color red = Color(0xFFFF1744);
const Color pink = Color(0xFFF06292);
const Color deepPink = Color(0xFFFC4B73);
const Color lightPurple = Color(0xFFAF7FDD);
const Color purple = Color(0xFF9C27B0);
const Color deepPurple = Color(0xFF673AB7);
const Color indigo = Color(0xFF3F51B5);
const Color blue = Color(0xFF2196F3);
const Color lightBlue = Color(0xFF03A9f4);
const Color cyan = Color(0xFF00BCD4);
const Color teal = Color(0xFF009688);
const Color warmGreen = Color(0xFF4CAf50);
const Color deepWarmGreen = Color(0xFF008000);
const Color green = Color(0xFF66BB6A);
const Color coolGreen = Color(0xFF00C076);
const Color deepCoolGreen = Color(0xFF03965E);
const Color lightGreen = Color(0xFF8BC34A);
const Color yellow = Color(0xFFFFEB3B);
const Color amber = Color(0xFFFFC107);
const Color deepAmber = Color(0xFFFEA200);
const Color orange = Color(0xFFF47739);
const Color deepOrange = Color(0xFFFF5722);
const Color lightBrown = Color(0xFFB9965E);
const Color brown = Color(0xFFA9653D);
const Color deepBrown = Color(0xFF795548);
const Color grey = Color(0xFF9E9E9E);
const Color deepGrey = Color(0xFF484848);
const Color blueGrey = Color(0xFF606F8D);
